### ISSUE TITLE
Python Example is Outdated

### ISSUE THREAD

**Issue by fvaliquette-splunk** [signalfx/splunk-otel-python#479]
[requirements.txt](https://github.com/signalfx/splunk-otel-python/blob/main/examples/falcon/requirements.txt) lists splunk-opentelemetry but it should be splunk-opentelemetry[all] as mentioned in [Spluk official doc](https://docs.splunk.com/observability/en/gdi/get-data-in/application/python/instrumentation/instrument-python-application.html#install-and-activate-the-python-agent). 

When not using [all], with default settings, we get below error.

`ValueError: exporter "otlp (otlp_proto_grpc)" not found. please make sure opentelemetry-exporter-otlp-proto-grpc is installed`

**Comment by billg-splunk** [comment]
Is there anything holding up this change?

Would be good to know if there is a reason not to use splunk-opentelemetry[all] in certain situations.

**Comment by pmcollins** [comment]
I'm not sure why `otlp` was put behind a Python extra. The next major version of Splunk Otel Python will include it by default unless we discover a reason not to.

In the meantime, I've opened [this PR](https://github.com/signalfx/splunk-otel-python/pull/508) for adding `[all]` to the requirements file for the example.

**Comment by billg-splunk** [comment]
Appreciate it Pablo!

**Comment by pmcollins** [comment]
Completed, closing.
