### ISSUE TITLE
Audit Compliance GDI specification pre-v1.7.0: Versioning

### ISSUE THREAD

**Issue by pellared** [signalfx/splunk-otel-python#558]
Review against https://github.com/signalfx/gdi-specification/blob/ce84954821bfe6ab6f6f1ed6cad5f87489293220/specification/versioning.md

**Comment by pellared** [comment]
@pmcollins, do you plan to make a major or minor bump? If it is planned to make a v2? If a v2 then what are the breaking changes planned?

**Comment by pmcollins** [comment]
Hi @pellared, thank you for the help.

The [release notes](https://github.com/signalfx/splunk-otel-python/blob/v2/RELEASE_NOTES.md) should describe the changes, but we can add more if there's anything missing.

The version is specified [here](https://github.com/signalfx/splunk-otel-python/blob/v2/src/splunk_otel/__about__.py#L16)   (`2.0.0a1`).

Any thoughts on how to conform to this part of the spec?
> Version numbers for releases MUST be less than 1.0.0 while experimental.
