### ISSUE TITLE
OTEL_RESOURCE_ATTRIBUTES=service.name=my-python-app is not working- SPLUNK_SERVICE_NAME is the only option

### ISSUE THREAD

**Issue by slernersplunk** [signalfx/splunk-otel-python#62]
OTEL_RESOURCE_ATTRIBUTES=service.name=my-python-app is not working

SPLUNK_SERVICE_NAME is the only option that works- yet the repo states that OTEL_RESOURCE_ATTRIBUTES=service.name=my-python-app is the right way...

GDI wizard also uses SPLUNK_SERVICE_NAME

**Comment by owais** [comment]
Support for SPLUNK_SERVICE_NAME will be completely removed in the upcoming version and OTEL_RESOURCE_ATTRIBTES will be the only way to set the service name. It should still work both ways in the current stable version. 

Please share library version and steps to reproduce.

**Comment by owais** [comment]
There might have been a bug in earleir versions. I did not verify it but I can verify latest version works correctly. Please update to 0.13.0 and see if it works now. (You'll need to use OTEL_SERVICE_NAME).

Release notes and upgrade steps:
https://github.com/signalfx/splunk-otel-python/releases/tag/v0.13.0
